# Generated by Django 3.1.2 on 2021-04-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Your title of event', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('city', models.CharField(default='Lviv', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('image', models.ImageField(default='/Users/nadiiapadalka/Downloads/sport_platform/backend/server/media/post_images/img.jpg', upload_to='events_images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
