# Generated by Django 3.1.2 on 2021-04-11 21:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210405_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subscribedUsers',
            field=jsonfield.fields.JSONField(blank=True, default={'usernames': {}}),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='/Users/nadiiapadalka/Downloads/sport_platform/backend/server/media/post_images/img.jpg', upload_to='events_images'),
        ),
    ]
