# Generated by Django 3.1.2 on 2021-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210417_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cretor',
            field=models.CharField(default='creator', max_length=255),
        ),
    ]
