# Generated by Django 3.1.2 on 2021-04-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_cretor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cretor',
            new_name='creator',
        ),
    ]
